sude: required
services:
    - docker

before_install:
    - docker build -t pimtchenkov/docker-react:test-ci -f Dockerfile.dev .

script:
    - docker run pimtchenkov/docker-react:test-ci npm run test
    
### deploy section
#deploy:
#    provide: elasticbeanstalk
#    region: "us-east-2"
#    app: "docker-react"
#    env: "DockerReact-env"
#    bucket_name: "elasticbeanstalk-us-east-2-768318074260"
#    bucket_path: "docker-react"
#    on:
#        branch: master
#    access_key_id: $AWS_ACCESS_KEY
#    secret_access_key: $AWS_SECRET_KEY
