version: '3'
services:
    tests:
        image: pimtchenkov/frontend:compose01
        stdin_open: true
        tty: true
        build:
            context: .
            dockerfile: Dockerfile.dev
        volumes:
            - /app/node_modules
            - .:/app
        command: ["npm","run","test"]
    main-server:
        image: pimtchenkov/frontend:compose01
        stdin_open: true
        tty: true
        build:
            context: .
            dockerfile: Dockerfile.dev
        ports:
            - "3000:3000"
        volumes:
            - /app/node_modules
            - .:/app
