version: '3'
services:
    main-server:
        image: pimtchenkov/frontend:compose01
        stdin_open: true
        tty: true
        build:
            context: .
            dockerfile: Dockerfile.test
        ports:
            - "3000:3000"
        volumes:
            - /app/node_modules
            - .:/app
